name:                huffman
version:             0.1.0.0
github:              "boginw/huffman"
license:             BSD3
author:              "Bogi Napoleon Wennerstrøm"
maintainer:          "bogi.wennerstrom@gmail.com"
copyright:           "2019 Bogi Napoleon Wennerstrøm"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/boginw/huffman#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- binary
- bytestring

library:
  source-dirs: src

executables:
  huffman-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - huffman

tests:
  huffman-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - huffman
